spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/careergps
    username: careergps_user
    password: your_password

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8080
