INSERT INTO skills (code, name, description) VALUES
('SK001','Problem Solving','Break down and solve challenges'),('SK002','Logical Thinking','Use clear reasoning'),('SK003','Critical Thinking','Evaluate ideas carefully'),('SK005','Attention to Detail','Notice important details'),('SK007','Data Analysis','Find meaning in data'),('SK008','Research','Find and evaluate information'),('SK011','Programming','Write computer programs'),('SK012','Software Development','Build software products'),('SK013','Mathematics','Work confidently with numbers'),('SK014','Engineering Design','Design practical solutions'),('SK016','Cybersecurity','Protect digital systems'),('SK019','AI / Machine Learning','Build intelligent systems'),('SK021','Verbal Communication','Explain ideas clearly'),('SK029','Teaching','Help others learn'),('SK031','Creativity','Create original ideas'),('SK032','Design Thinking','Solve user problems creatively'),('SK033','Graphic Design','Create visual communication'),('SK041','Leadership','Guide a group'),('SK046','Project Management','Plan and deliver work'),('SK051','Accounting','Manage financial records'),('SK054','Marketing','Promote products or services'),('SK061','Patient Care','Support patient wellbeing'),('SK062','Diagnosis','Identify health conditions'),('SK063','Medical Knowledge','Apply healthcare knowledge'),('SK064','Empathy','Understand people''s feelings'),('SK071','Teaching','Plan and deliver learning'),('SK081','Physical Fitness','Maintain physical readiness'),('SK087','Agriculture','Understand crop and farm work'),('SK091','Scientific Method','Test ideas using evidence'),('SK097','Statistical Analysis','Analyse numerical evidence');
INSERT INTO subjects (code, name, description) VALUES
('SUB001','Mathematics','Numbers, logic and problem solving'),('SUB002','Physics','Matter, energy and motion'),('SUB003','Chemistry','Materials and chemical change'),('SUB004','Biology','Living organisms and health'),('SUB005','Computer Science','Computing and programming'),('SUB006','Economics','Markets and economies'),('SUB007','Commerce','Business and accounting'),('SUB008','History','Past events and societies'),('SUB009','Arts & Design','Visual and creative expression'),('SUB010','Political Science','Government and public policy'),('SUB011','Physical Education','Fitness and sports'),('SUB012','Agriculture','Food, crops and farming');
INSERT INTO traits (code, name, description) VALUES
('LOG','Logical','Uses clear reasoning'),('PRS','Problem Solver','Enjoys solving challenges'),('CRI','Critical Thinker','Evaluates ideas carefully'),('STR','Strategic','Plans ahead'),('RES','Research Oriented','Enjoys finding evidence'),('DAT','Data Oriented','Enjoys patterns in data'),('INV','Investigative','Enjoys discovering how things work'),('CUR','Curious','Wants to learn more'),
('SYS','System Thinker','Understands connected systems'),('BLD','Builder','Enjoys making things'),('ENG','Engineering Mindset','Enjoys practical technical design'),('AUT','Automation Oriented','Looks for efficient processes'),('DIG','Digital Creator','Creates with digital tools'),('INN','Innovation Focused','Enjoys new ideas'),('PRO','Process Oriented','Improves how work gets done'),('SOL','Solution Designer','Designs useful solutions'),
('EMP','Empathetic','Understands people''s feelings'),('HLP','Helpful','Enjoys supporting others'),('SUP','Supportive','Likes being there for people'),('LIS','Listener','Pays attention to others'),('MEN','Mentor','Enjoys guiding people'),('TEA','Teacher','Enjoys helping people learn'),('TMO','Team Player','Works well with others'),('REL','Relationship Builder','Builds trust with people'),('SER','Service Oriented','Wants to serve others'),
('DEC','Decision Maker','Makes thoughtful choices'),('ORG','Organizer','Keeps work organised'),('INF','Influencer','Can persuade others'),('RSP','Responsible','Takes ownership'),('VIS','Visionary','Thinks about future possibilities'),('ENT','Entrepreneurial','Sees opportunities'),('NEG','Negotiator','Finds agreement'),('MOT','Motivator','Encourages others'),('MAN','Managerial','Coordinates people and work'),
('ART','Artistic','Enjoys visual expression'),('DES','Designer','Enjoys designing things'),('STO','Storyteller','Enjoys communicating through stories'),('VTH','Visual Thinker','Thinks through images'),('IMA','Imaginative','Creates possibilities'),('CON','Content Creator','Creates media'),('EXP','Expressive','Shares ideas openly'),('AES','Aesthetic Thinker','Cares about visual quality'),
('SCI','Scientific','Interested in evidence and experiments'),('EXM','Experimenter','Likes testing ideas'),('OBS','Observer','Notices changes carefully'),('EVI','Evidence Seeker','Looks for proof'),('EXPLO','Explorer','Enjoys discovering'),('LAB','Laboratory Oriented','Enjoys lab work'),('NAT','Nature Enthusiast','Interested in natural world'),('RSC','Researcher','Enjoys deep study'),
('BIZ','Business Minded','Interested in how organisations work'),('FIN','Financial Thinker','Enjoys finance and money'),('RSK','Risk Taker','Comfortable with calculated risk'),('OPP','Opportunity Finder','Notices possibilities'),('MAR','Market Oriented','Interested in customers and markets'),('COMR','Commercial Thinker','Focuses on value and business'),('SAL','Sales Oriented','Enjoys convincing customers'),('INVST','Investor Mindset','Thinks about long-term value'),('OPT','Resource Optimizer','Uses resources wisely'),('GRO','Growth Oriented','Wants to improve and grow'),
('OUT','Outdoor Oriented','Enjoys working outside'),('PHY','Physically Active','Likes physical activity'),('ADV','Adventurous','Enjoys new experiences'),('FLD','Field Worker','Comfortable working in the field'),('HND','Hands-On','Prefers practical work'),('DIS','Disciplined','Follows routines carefully'),('COU','Courageous','Stays calm in difficult situations'),('ACT','Action Oriented','Likes taking action'),('RSL','Resilient','Recovers from setbacks'),('OPR','Operational','Enjoys practical operations')
ON CONFLICT (code) DO NOTHING;
