INSERT INTO career_categories (name, description, code) VALUES
('Education','Teaching and learning careers','EDU'),('Science & Research','Science and research careers','SCI'),('Law','Legal careers','LAW'),('Defense','National security careers','DEF'),('Sports','Sports and fitness careers','SPT'),('Skilled Trades','Practical technical careers','TRD'),('Agriculture','Food and farming careers','AGR'),('Hospitality','Travel, food and service careers','HOS'),('Media','Media and communication careers','MEDI') ON CONFLICT (code) DO NOTHING;
UPDATE careers SET category_id=(SELECT id FROM career_categories WHERE code='DEF') WHERE code='DEF001';
INSERT INTO careers (category_id,code,name,description,reality_check,work_environment) VALUES
((SELECT id FROM career_categories WHERE code='TECH'),'TECH004','AI Engineer','Builds systems that use artificial intelligence.','Requires maths, programming and regular learning.','Works with software and data teams.'),
((SELECT id FROM career_categories WHERE code='TECH'),'TECH005','Cloud Engineer','Builds and maintains cloud systems.','Requires strong systems knowledge.','Works with infrastructure and development teams.'),
((SELECT id FROM career_categories WHERE code='TECH'),'TECH006','DevOps Engineer','Improves how software is built and released.','Requires programming and operations skills.','Works across development and operations teams.'),
((SELECT id FROM career_categories WHERE code='TECH'),'TECH007','Mobile App Developer','Builds applications for phones and tablets.','Needs regular practice and a portfolio.','Works in product teams or independently.'),
((SELECT id FROM career_categories WHERE code='TECH'),'TECH008','Web Developer','Builds websites and web applications.','Skills and project work matter strongly.','Works in agencies, product teams or freelance.'),
((SELECT id FROM career_categories WHERE code='HLTH'),'HLTH004','Dentist','Diagnoses and treats oral health problems.','Requires a long study path and precision.','Works in clinics or hospitals.'),
((SELECT id FROM career_categories WHERE code='HLTH'),'HLTH005','Pharmacist','Guides the safe use of medicines.','Needs scientific accuracy and responsibility.','Works in hospitals, pharmacies or industry.'),
((SELECT id FROM career_categories WHERE code='HLTH'),'HLTH006','Medical Lab Technologist','Performs tests that support diagnosis.','Requires laboratory discipline and detail.','Works in laboratories and hospitals.'),
((SELECT id FROM career_categories WHERE code='HLTH'),'HLTH007','Nutritionist','Helps people plan healthy diets.','Needs science knowledge and communication.','Works in clinics, wellness centres or independently.'),
((SELECT id FROM career_categories WHERE code='HLTH'),'HLTH008','Psychologist','Studies behaviour and supports mental wellbeing.','Requires higher education and careful listening.','Works in clinics, schools or organisations.'),
((SELECT id FROM career_categories WHERE code='BUS'),'BUS004','Financial Analyst','Analyses financial performance and investment choices.','Needs strong numbers and business awareness.','Works in banks, firms and companies.'),
((SELECT id FROM career_categories WHERE code='BUS'),'BUS005','Investment Banker','Advises organisations on major financial decisions.','Long hours and competition are common.','Works in financial institutions.'),
((SELECT id FROM career_categories WHERE code='BUS'),'BUS006','Entrepreneur','Builds and runs a business.','Income and outcomes are uncertain.','Works independently with a team.'),
((SELECT id FROM career_categories WHERE code='BUS'),'BUS007','HR Manager','Supports hiring and people development.','Needs communication and fairness.','Works in organisations across industries.'),
((SELECT id FROM career_categories WHERE code='BUS'),'BUS008','Operations Manager','Keeps business operations running smoothly.','Needs planning and problem solving.','Works across business teams.'),
((SELECT id FROM career_categories WHERE code='GOV'),'GOV003','Indian Foreign Service Officer','Represents India in international relations.','Requires clearing UPSC and willingness to relocate.','Works in India and overseas.'),
((SELECT id FROM career_categories WHERE code='GOV'),'GOV004','Public Policy Analyst','Studies policies and their social impact.','Needs research and writing skills.','Works with government, research groups or NGOs.'),
((SELECT id FROM career_categories WHERE code='EDU'),'EDU001','School Teacher','Teaches and supports school students.','Requires preparation and patience.','Works in schools.'),
((SELECT id FROM career_categories WHERE code='EDU'),'EDU002','Professor','Teaches and researches in higher education.','Usually needs postgraduate study.','Works in colleges and universities.'),
((SELECT id FROM career_categories WHERE code='EDU'),'EDU003','Special Educator','Supports students with diverse learning needs.','Requires empathy and specialised training.','Works in schools and support centres.'),
((SELECT id FROM career_categories WHERE code='EDU'),'EDU004','Career Counselor','Helps students make education and career decisions.','Needs listening and updated career knowledge.','Works in schools, colleges or independently.'),
((SELECT id FROM career_categories WHERE code='EDU'),'EDU005','Corporate Trainer','Builds workplace learning programmes.','Needs communication and facilitation skills.','Works in companies or consulting.'),
((SELECT id FROM career_categories WHERE code='ART'),'ART004','Fashion Designer','Designs clothing and accessories.','Portfolio and industry exposure matter.','Works in studios, brands or independently.'),
((SELECT id FROM career_categories WHERE code='ART'),'ART005','Interior Designer','Designs useful and attractive indoor spaces.','Needs design skills and client communication.','Works in design firms or independently.'),
((SELECT id FROM career_categories WHERE code='ART'),'ART006','Photographer','Creates photographs for people, brands and media.','Portfolio and practice are essential.','Works freelance or with media and brands.'),
((SELECT id FROM career_categories WHERE code='ART'),'ART007','Film Editor','Shapes video stories from recorded footage.','Needs software skill and patience.','Works in studios, media or freelance.'),
((SELECT id FROM career_categories WHERE code='ART'),'ART008','Content Creator','Creates useful or entertaining digital content.','Income can be uncertain and consistency matters.','Works independently or with media teams.'),
((SELECT id FROM career_categories WHERE code='SCI'),'SCI001','Research Scientist','Studies questions through scientific research.','Often needs postgraduate study.','Works in laboratories, universities or industry.'),
((SELECT id FROM career_categories WHERE code='SCI'),'SCI002','Biologist','Studies living organisms and ecosystems.','Needs science study and field or lab work.','Works in labs, research and conservation.'),
((SELECT id FROM career_categories WHERE code='SCI'),'SCI003','Chemist','Studies substances and chemical processes.','Requires laboratory safety and accuracy.','Works in labs, manufacturing and research.'),
((SELECT id FROM career_categories WHERE code='SCI'),'SCI004','Physicist','Studies matter, energy and physical laws.','Usually needs advanced mathematics.','Works in research, education or technology.'),
((SELECT id FROM career_categories WHERE code='SCI'),'SCI005','Environmental Scientist','Studies and protects the environment.','May involve fieldwork and research.','Works in research, government and consulting.'),
((SELECT id FROM career_categories WHERE code='LAW'),'LAW001','Lawyer','Advises clients and represents legal cases.','Requires legal study and clear communication.','Works in firms, courts or organisations.'),
((SELECT id FROM career_categories WHERE code='LAW'),'LAW002','Corporate Lawyer','Advises businesses on legal matters.','Needs commercial knowledge and long hours.','Works in law firms and companies.'),
((SELECT id FROM career_categories WHERE code='LAW'),'LAW003','Legal Advisor','Helps organisations understand legal obligations.','Requires law degree and careful analysis.','Works in companies, government or NGOs.'),
((SELECT id FROM career_categories WHERE code='LAW'),'LAW004','Judge','Decides cases in courts after a legal career.','Requires extensive legal experience.','Works in the judicial system.'),
((SELECT id FROM career_categories WHERE code='SPT'),'SPT001','Athlete','Competes in a chosen sport.','Income and selection can be uncertain.','Trains and competes in sports settings.'),
((SELECT id FROM career_categories WHERE code='SPT'),'SPT002','Sports Coach','Trains athletes and teams.','Needs sport knowledge and communication.','Works with teams, academies or schools.'),
((SELECT id FROM career_categories WHERE code='SPT'),'SPT003','Fitness Trainer','Helps people improve physical fitness.','Needs certification and client trust.','Works in gyms, studios or independently.'),
((SELECT id FROM career_categories WHERE code='SPT'),'SPT004','Sports Analyst','Uses data to improve sports performance.','Needs sports knowledge and data skills.','Works with teams, media or technology firms.'),
((SELECT id FROM career_categories WHERE code='TRD'),'TRD001','Electrician','Installs and repairs electrical systems.','Requires safety training and hands-on work.','Works on homes, sites and facilities.'),
((SELECT id FROM career_categories WHERE code='TRD'),'TRD002','Plumber','Installs and repairs water systems.','Requires practical training and physical work.','Works on homes, buildings and sites.'),
((SELECT id FROM career_categories WHERE code='TRD'),'TRD003','Automotive Technician','Repairs and maintains vehicles.','Requires technical practice and tools.','Works in garages and service centres.'),
((SELECT id FROM career_categories WHERE code='TRD'),'TRD004','Welder','Joins metal parts for products and construction.','Safety and precision are essential.','Works in workshops and construction.'),
((SELECT id FROM career_categories WHERE code='TRD'),'TRD005','Carpenter','Builds and repairs wooden structures.','Needs practical skill and precision.','Works in workshops and construction.'),
((SELECT id FROM career_categories WHERE code='AGR'),'AGR001','Agricultural Scientist','Improves crops, soil and farming methods.','Needs science knowledge and fieldwork.','Works in research, government and industry.'),
((SELECT id FROM career_categories WHERE code='AGR'),'AGR002','Horticulturist','Grows fruits, vegetables and ornamental plants.','Needs plant knowledge and fieldwork.','Works in farms, nurseries and research.'),
((SELECT id FROM career_categories WHERE code='AGR'),'AGR003','Forestry Officer','Protects forests and natural resources.','May require competitive examinations and fieldwork.','Works in forest and government services.'),
((SELECT id FROM career_categories WHERE code='AGR'),'AGR004','Farm Manager','Plans and manages farm operations.','Needs practical knowledge and business skills.','Works on farms and agribusinesses.'),
((SELECT id FROM career_categories WHERE code='AGR'),'AGR005','Food Technologist','Improves food products and safety.','Needs science and quality awareness.','Works in food manufacturing and labs.'),
((SELECT id FROM career_categories WHERE code='HOS'),'HOS001','Hotel Manager','Manages hospitality operations and guest experience.','Needs service skills and flexible hours.','Works in hotels and resorts.'),
((SELECT id FROM career_categories WHERE code='HOS'),'HOS002','Chef','Plans and prepares food professionally.','Requires practice and demanding shifts.','Works in restaurants, hotels and kitchens.'),
((SELECT id FROM career_categories WHERE code='HOS'),'HOS003','Travel Consultant','Helps people plan travel experiences.','Needs destination knowledge and service skills.','Works in travel companies or independently.'),
((SELECT id FROM career_categories WHERE code='HOS'),'HOS004','Event Manager','Plans and runs events.','Needs organisation and calm under pressure.','Works in agencies, companies or independently.'),
((SELECT id FROM career_categories WHERE code='MEDI'),'MEDIA001','Journalist','Researches and reports news and stories.','Needs writing, accuracy and persistence.','Works in newsrooms and digital media.'),
((SELECT id FROM career_categories WHERE code='MEDI'),'MEDIA002','News Anchor','Presents news for audiences.','Needs communication and current-affairs knowledge.','Works in television and digital media.'),
((SELECT id FROM career_categories WHERE code='MEDI'),'MEDIA003','Digital Marketer','Uses digital channels to reach audiences.','Needs regular learning and data awareness.','Works in agencies, brands or independently.'),
((SELECT id FROM career_categories WHERE code='MEDI'),'MEDIA004','Social Media Manager','Plans and manages social media communication.','Needs creativity and quick responses.','Works with brands, agencies or creators.'),
((SELECT id FROM career_categories WHERE code='MEDI'),'MEDIA005','Video Producer','Plans and produces video content.','Needs coordination and production skills.','Works in studios, agencies or independently.');

INSERT INTO career_trait_mapping (career_id, trait_id, weight)
SELECT c.id, t.id, 4 FROM careers c JOIN career_categories cc ON cc.id=c.category_id JOIN traits t ON t.code = CASE cc.code WHEN 'TECH' THEN 'TEC' WHEN 'HLTH' THEN 'SOC' WHEN 'BUS' THEN 'LDR' WHEN 'ART' THEN 'CRT' WHEN 'GOV' THEN 'LDR' WHEN 'EDU' THEN 'COM' WHEN 'SCI' THEN 'SCI' WHEN 'LAW' THEN 'COM' WHEN 'DEF' THEN 'DIS' WHEN 'SPT' THEN 'PHY' WHEN 'TRD' THEN 'HND' WHEN 'AGR' THEN 'NAT' WHEN 'HOS' THEN 'SOC' WHEN 'MEDI' THEN 'STO' END ON CONFLICT (career_id, trait_id) DO NOTHING;
INSERT INTO career_skill_mapping (career_id, skill_id, weight)
SELECT c.id, s.id, 4 FROM careers c JOIN career_categories cc ON cc.id=c.category_id JOIN skills s ON s.code = CASE cc.code WHEN 'TECH' THEN 'SK011' WHEN 'HLTH' THEN 'SK064' WHEN 'BUS' THEN 'SK046' WHEN 'ART' THEN 'SK031' WHEN 'GOV' THEN 'SK008' WHEN 'EDU' THEN 'SK071' WHEN 'SCI' THEN 'SK091' WHEN 'LAW' THEN 'SK021' WHEN 'DEF' THEN 'SK081' WHEN 'SPT' THEN 'SK081' WHEN 'TRD' THEN 'SK014' WHEN 'AGR' THEN 'SK087' WHEN 'HOS' THEN 'SK021' WHEN 'MEDI' THEN 'SK021' END ON CONFLICT (career_id, skill_id) DO NOTHING;
INSERT INTO career_subject_mapping (career_id, subject_id, weight)
SELECT c.id, s.id, 4 FROM careers c JOIN career_categories cc ON cc.id=c.category_id JOIN subjects s ON s.code = CASE cc.code WHEN 'TECH' THEN 'SUB005' WHEN 'HLTH' THEN 'SUB004' WHEN 'BUS' THEN 'SUB007' WHEN 'ART' THEN 'SUB009' WHEN 'GOV' THEN 'SUB010' WHEN 'EDU' THEN 'SUB008' WHEN 'SCI' THEN 'SUB002' WHEN 'LAW' THEN 'SUB008' WHEN 'DEF' THEN 'SUB011' WHEN 'SPT' THEN 'SUB011' WHEN 'TRD' THEN 'SUB002' WHEN 'AGR' THEN 'SUB012' WHEN 'HOS' THEN 'SUB007' WHEN 'MEDI' THEN 'SUB009' END ON CONFLICT (career_id, subject_id) DO NOTHING;

INSERT INTO routes (career_id, route_name, route_description, route_type, duration_months, cost_band, entrance_exams, competition_level, relocation_needed)
SELECT c.id, 'Standard route', 'Class 10 → Relevant stream or training → Qualification → ' || c.name, 'STANDARD', 48, 'Varies', 'Check institution requirements', 'Varies', false FROM careers c WHERE NOT EXISTS (SELECT 1 FROM routes r WHERE r.career_id=c.id);
INSERT INTO route_steps (route_id, step_order, title, detail)
SELECT r.id, 1, 'Class 10', 'Complete school and explore the relevant subjects.' FROM routes r WHERE NOT EXISTS (SELECT 1 FROM route_steps rs WHERE rs.route_id=r.id);
INSERT INTO route_steps (route_id, step_order, title, detail)
SELECT r.id, 2, 'Education or training', 'Choose the route and qualification that fit your goals and circumstances.' FROM routes r WHERE NOT EXISTS (SELECT 1 FROM route_steps rs WHERE rs.route_id=r.id);
INSERT INTO route_steps (route_id, step_order, title, detail)
SELECT r.id, 3, c.name, 'Build skills, experience and a portfolio where relevant.' FROM routes r JOIN careers c ON c.id=r.career_id WHERE NOT EXISTS (SELECT 1 FROM route_steps rs WHERE rs.route_id=r.id);
